### ISSUE TITLE
Could you help to provide browser support?

### ISSUE THREAD

**Issue by JimmyLv** [syaning/zhihu-api#1]

**Comment by syaning** [comment]
Since browsers could not send requests directly to zhihu because of the Cross Domain issue. It seems that you have to write your server-side code to support browser access. May be you could build a restful API using this project with Express/Koa.

**Comment by JimmyLv** [comment]
Yep, I has tried a series of ways to fetch data from zhihu in browser directly. Aha, using iframe but got `'X-Frame-Options' to 'DENY'`, using Ajax (`$http`'s transformResponse in angular) but got CORS limitation, using JSONP but got `Can't convert to JSON from XML`, using JSONP-X by [Yahoo's YQL](https://developer.yahoo.com/yql/) but only can fetch the home page(<http://www.zhihu.com>),

You can tried this link which already be able to provide json api: <https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20html%20where%20url%3D'https%3A%2F%2Fwww.zhihu.com'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys>

Just shared these to you, finally I think I should let it go and forgive hack zhihu just in browser.

**Comment by JimmyLv** [comment]
Impossible!!! I tried again but work!!!

Could you help to check again?

https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20html%20where%20url%3D'https%3A%2F%2Fwww.zhihu.com%2Fquestion%2F19709168%2Fanswer%2F15810088'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys
