### ISSUE TITLE
Request.setAuth函数

### ISSUE THREAD

**Issue by yizhiheng** [syaning/zhihu-api#10]
现在是用`Cookie`里的`z_c0`给`header.Authorization`赋值
```js
this.headers['Authorization'] = `Bearer ${parsedCookie.z_c0}`
```
能给Request module加一个函数, 比如`setAuth`或者`setAuthorization`来overwrite这个值吗?

**Comment by syaning** [comment]
新增了`api.auth`方法 （https://github.com/syaning/zhihu-api/blob/2.4.2/index.js#L30）

不过由于一部分接口还是依赖于Cookie（即抓取页面然后解析），一部分接口依赖于Auth header（直接调用官方api），该方法只能影响到依赖Auth header的接口，对于依赖Cookie的接口暂时没有任何效果。

发了2.4.2版本。

**Comment by yizhiheng** [comment]
感谢回复
