### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by ibio** [syaning/zhihu-api#2]
Hi, I continue getting the following error. My environment is v5.10.1. Also, my server is located in New York. Will that effect the code? Thanks.

Trace: [SyntaxError: Unexpected end of input]
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by syaning** [comment]
Also, I use a U.S. proxy and I have got this issue several times. It seems that overseas requests may get a bad response sometimes.

Could you please tell me which API you use? I will test is again and give feedback to you.

**Comment by ibio** [comment]
Sure. I was use the sample code usage you provided:
`const fs = require('fs')
const api = require('zhihu-api')

// cookie must be set before any request
api.cookie(fs.readFileSync('./cookie'))

api.user('excited-vczh').detail()
    .then(console.log.bind(console))
    .catch(console.trace.bind(console))`

Also, when I run the example, I did not get any result. Have you had this situation before?

**Comment by syaning** [comment]
I can get the correct response.
![2016-04-13_103841](https://cloud.githubusercontent.com/assets/7125133/14481295/18ee0236-0164-11e6-8e2a-23f56998d161.png)

Have you set the cookie correctly?

First, check if the `cookie` file exists. Second, just copy your cookie(Chrome DevTool → Network → Request Headers → Cookie) to the file.

**Comment by ibio** [comment]
Yes, for sure I copied all my cookies to the cookie file.

**Comment by ibio** [comment]
Hi, eventually it works on my windows OS. I am trying to figure out why it did not work on my CentOS server. Thank you so much.
