### ISSUE TITLE
api.topic(topicId).hierarchy()无法获取完整子话题

### ISSUE THREAD

**Issue by subdueego** [syaning/zhihu-api#3]
我试着读取了一下“「未归类」话题”
结果没读取完整的子话题

**Comment by syaning** [comment]
![2016-04-21_110401](https://cloud.githubusercontent.com/assets/7125133/14696840/00b385da-07b1-11e6-828e-0b4797ea371d.png)

[https://www.zhihu.com/topic/19776751/organize](https://www.zhihu.com/topic/19776751/organize)

如图，目前子话题的获取是在这个页面。对于大部分话题来说，子话题不会特别多，因此红框部分会显示所有的子话题。对于未归类话题，子话题有30K+，因此这里只显示部分话题，在抓取的时候只抓取了显示出来的部分。

如果要获取所有的子话题，相关页面是[https://www.zhihu.com/topic/19776751/organize/entire](https://www.zhihu.com/topic/19776751/organize/entire)。需要发起多个请求，并且每个请求的参数依赖于上一个请求的结果。相对麻烦一些，暂时没有实现相关接口。
