### ISSUE TITLE
topic.hierarchy doesn't seem to work

### ISSUE THREAD

**Issue by kinhunt** [syaning/zhihu-api#6]
returns:

{ id: 0,
  tid: 0,
  link: '',
  name: '',
  avatar: '',
  followers: 0,
  parents: [],
  children: [],
  crawltime: 1470400871707 }

btw, cool project

**Comment by syaning** [comment]
Thx~
But I got the exact result.
It seems that your cookie is invalid (incorrect or expired), pls check it.

**Comment by kinhunt** [comment]
You are write. wrong cookie indeed. Thank you.

**Comment by lihaocruiser** [comment]
I have the the same problem but don't know how to fix it.
I run `document.cookie` in browser console and copied the string into the cookie file. It looks like
```
_za=xxxx; d_c0="xxxx"; _zap=xxxx; q_c1=xxxx; l_cap_id="xxxx"; cap_id="xxxx"; r_cap_id="xxxx"; login="xxxx"; _ga=xxxx; _xsrf=xxxx; etc...
```
where did i go wrong?

**Comment by syaning** [comment]
@lihaocruiser the authorization token (aka `z_c0`) in cookie is httpOnly. So `document.cookie` does not include this value. You should copy cookie from http headers.

**Comment by yizhiheng** [comment]
@lihaocruiser FYI, if you use chrome, there is a extension called `EditThisCookie`

**Comment by lihaocruiser** [comment]
@syaning @yizhiheng got it. thanks a lot!
