### ISSUE TITLE
暂不支持新版个人主页的解析

### ISSUE THREAD

**Issue by syaning** [syaning/zhihu-api#8]
新版主页例如 [https://www.zhihu.com/people/jiangxiaozhang/activities](https://www.zhihu.com/people/jiangxiaozhang/activities)

**Comment by yizhiheng** [comment]
请问正在开发吗? 可以帮你做一部分...

**Comment by syaning** [comment]
我看了下，关于用户方面：

- 目前只有少数用户是新版主页
- 和用户相关的所有接口（提问、回答等等）都变了
- 目前新版主页还在测试阶段，还存在着一些bug

所以我的想法是先等一等，等新版正式上线了再去实现，不然可能会一直要跟着知乎的页面来改。

另外，到时候不知道话题／问题等其它相关页面会不会有所变化。

新建了branch 2.x，用于开发针对新版页面的更新。

**Comment by syaning** [comment]
v2.0.0 now supports new homepage.
